name: CI pipeline

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install ansible
      run: pip install ansible
    - name: Check ansible version
      run: ansible --version  
    - name: Lint test
      run: ansible-playbook dhcpd/tests/test.yml --syntax-check